FROM ubi8/ubi:8.3
MAINTAINER Neil 

LABEL description="A custom Apache container based on UBI 8"

ENV PORT 8080

RUN yum install -y httpd && \
    yum clean all

RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/
RUN echo "Hello World!" > /var/www/html/index.html

USER apache

EXPOSE ${PORT}

COPY ./src/ /var/www/html/

CMD ["httpd", "-D", "FOREGROUND"]
